spring:
  application:
    name: Product-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/MicroService
  web:
    cors:
      allowed-origin-patterns: http://localhost:3000
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS

server:
  port: 8083

eureka:
  instance: 
    prefer-ip-address: true
  client:
    register-with-eureka: true 
    fetch-registry: true
  server-url:
    defaultZone: http://localhost:8761/eureka 


